// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1408013620;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_spatial_audio_sandbox',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<FileSourceInfo> crateApiEngineAddFileSource({
    required List<int> bytes,
    required bool looping,
    required double x,
    required double y,
    required double z,
    required double gain,
  });

  Future<int> crateApiEngineAddSource({
    required SourceKindWire kind,
    required double x,
    required double y,
    required double z,
    required double gain,
  });

  EngineInfoWire? crateApiEngineEngineInfo();

  Future<EngineInfoWire> crateApiEngineEngineStart();

  Future<void> crateApiEngineEngineStop();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiEnginePrepareFileSource({required List<int> bytes});

  void crateApiEngineRecenter();

  Future<void> crateApiEngineRemoveSource({required int id});

  Future<void> crateApiEngineRenderOrbitWav({
    required String path,
    required SourceKindWire kind,
    required double seconds,
    required double radiusM,
    required double elevDeg,
    required double periodS,
  });

  Future<void> crateApiEngineRenderStaticWav({
    required String path,
    required SourceKindWire kind,
    required double seconds,
    required double azDeg,
    required double elevDeg,
    required double distM,
  });

  void crateApiEngineSeekSource({required int id, required double posS});

  void crateApiEngineSetHeadPose({
    required double w,
    required double x,
    required double y,
    required double z,
    required double gx,
    required double gy,
    required double gz,
  });

  void crateApiEngineSetPredictMs({required double ms});

  void crateApiEngineSetSourceGain({required int id, required double gain});

  void crateApiEngineSetSourcePosition({
    required int id,
    required double x,
    required double y,
    required double z,
  });

  void crateApiEngineSetSpatialParams({
    required double width,
    required double wet,
    required double ildDb,
  });

  void crateApiEngineSetSpatialWidth({required double w});

  void crateApiEngineSetYawOnly({required bool yawOnly});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FileSourceInfo> crateApiEngineAddFileSource({
    required List<int> bytes,
    required bool looping,
    required double x,
    required double y,
    required double z,
    required double gain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_bool(looping, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_f_32(z, serializer);
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_file_source_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAddFileSourceConstMeta,
        argValues: [bytes, looping, x, y, z, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAddFileSourceConstMeta =>
      const TaskConstMeta(
        debugName: "add_file_source",
        argNames: ["bytes", "looping", "x", "y", "z", "gain"],
      );

  @override
  Future<int> crateApiEngineAddSource({
    required SourceKindWire kind,
    required double x,
    required double y,
    required double z,
    required double gain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_source_kind_wire(kind, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_f_32(z, serializer);
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAddSourceConstMeta,
        argValues: [kind, x, y, z, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAddSourceConstMeta => const TaskConstMeta(
    debugName: "add_source",
    argNames: ["kind", "x", "y", "z", "gain"],
  );

  @override
  EngineInfoWire? crateApiEngineEngineInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_engine_info_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineInfoConstMeta =>
      const TaskConstMeta(debugName: "engine_info", argNames: []);

  @override
  Future<EngineInfoWire> crateApiEngineEngineStart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_info_wire,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineEngineStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineStartConstMeta =>
      const TaskConstMeta(debugName: "engine_start", argNames: []);

  @override
  Future<void> crateApiEngineEngineStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineStopConstMeta =>
      const TaskConstMeta(debugName: "engine_stop", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiEnginePrepareFileSource({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePrepareFileSourceConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePrepareFileSourceConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_file_source",
        argNames: ["bytes"],
      );

  @override
  void crateApiEngineRecenter() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineRecenterConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRecenterConstMeta =>
      const TaskConstMeta(debugName: "recenter", argNames: []);

  @override
  Future<void> crateApiEngineRemoveSource({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineRemoveSourceConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRemoveSourceConstMeta =>
      const TaskConstMeta(debugName: "remove_source", argNames: ["id"]);

  @override
  Future<void> crateApiEngineRenderOrbitWav({
    required String path,
    required SourceKindWire kind,
    required double seconds,
    required double radiusM,
    required double elevDeg,
    required double periodS,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_source_kind_wire(kind, serializer);
          sse_encode_f_32(seconds, serializer);
          sse_encode_f_32(radiusM, serializer);
          sse_encode_f_32(elevDeg, serializer);
          sse_encode_f_32(periodS, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRenderOrbitWavConstMeta,
        argValues: [path, kind, seconds, radiusM, elevDeg, periodS],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRenderOrbitWavConstMeta =>
      const TaskConstMeta(
        debugName: "render_orbit_wav",
        argNames: ["path", "kind", "seconds", "radiusM", "elevDeg", "periodS"],
      );

  @override
  Future<void> crateApiEngineRenderStaticWav({
    required String path,
    required SourceKindWire kind,
    required double seconds,
    required double azDeg,
    required double elevDeg,
    required double distM,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_source_kind_wire(kind, serializer);
          sse_encode_f_32(seconds, serializer);
          sse_encode_f_32(azDeg, serializer);
          sse_encode_f_32(elevDeg, serializer);
          sse_encode_f_32(distM, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRenderStaticWavConstMeta,
        argValues: [path, kind, seconds, azDeg, elevDeg, distM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRenderStaticWavConstMeta =>
      const TaskConstMeta(
        debugName: "render_static_wav",
        argNames: ["path", "kind", "seconds", "azDeg", "elevDeg", "distM"],
      );

  @override
  void crateApiEngineSeekSource({required int id, required double posS}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_f_32(posS, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSeekSourceConstMeta,
        argValues: [id, posS],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSeekSourceConstMeta =>
      const TaskConstMeta(debugName: "seek_source", argNames: ["id", "posS"]);

  @override
  void crateApiEngineSetHeadPose({
    required double w,
    required double x,
    required double y,
    required double z,
    required double gx,
    required double gy,
    required double gz,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(w, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_f_32(z, serializer);
          sse_encode_f_32(gx, serializer);
          sse_encode_f_32(gy, serializer);
          sse_encode_f_32(gz, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetHeadPoseConstMeta,
        argValues: [w, x, y, z, gx, gy, gz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetHeadPoseConstMeta => const TaskConstMeta(
    debugName: "set_head_pose",
    argNames: ["w", "x", "y", "z", "gx", "gy", "gz"],
  );

  @override
  void crateApiEngineSetPredictMs({required double ms}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(ms, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetPredictMsConstMeta,
        argValues: [ms],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetPredictMsConstMeta =>
      const TaskConstMeta(debugName: "set_predict_ms", argNames: ["ms"]);

  @override
  void crateApiEngineSetSourceGain({required int id, required double gain}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_f_32(gain, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetSourceGainConstMeta,
        argValues: [id, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetSourceGainConstMeta =>
      const TaskConstMeta(
        debugName: "set_source_gain",
        argNames: ["id", "gain"],
      );

  @override
  void crateApiEngineSetSourcePosition({
    required int id,
    required double x,
    required double y,
    required double z,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_f_32(z, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetSourcePositionConstMeta,
        argValues: [id, x, y, z],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetSourcePositionConstMeta =>
      const TaskConstMeta(
        debugName: "set_source_position",
        argNames: ["id", "x", "y", "z"],
      );

  @override
  void crateApiEngineSetSpatialParams({
    required double width,
    required double wet,
    required double ildDb,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(width, serializer);
          sse_encode_f_32(wet, serializer);
          sse_encode_f_32(ildDb, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetSpatialParamsConstMeta,
        argValues: [width, wet, ildDb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetSpatialParamsConstMeta =>
      const TaskConstMeta(
        debugName: "set_spatial_params",
        argNames: ["width", "wet", "ildDb"],
      );

  @override
  void crateApiEngineSetSpatialWidth({required double w}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(w, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetSpatialWidthConstMeta,
        argValues: [w],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetSpatialWidthConstMeta =>
      const TaskConstMeta(debugName: "set_spatial_width", argNames: ["w"]);

  @override
  void crateApiEngineSetYawOnly({required bool yawOnly}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(yawOnly, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSetYawOnlyConstMeta,
        argValues: [yawOnly],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetYawOnlyConstMeta =>
      const TaskConstMeta(debugName: "set_yaw_only", argNames: ["yawOnly"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EngineInfoWire dco_decode_box_autoadd_engine_info_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_engine_info_wire(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  EngineInfoWire dco_decode_engine_info_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return EngineInfoWire(
      backend: dco_decode_String(arr[0]),
      api: dco_decode_String(arr[1]),
      sampleRate: dco_decode_u_32(arr[2]),
      channels: dco_decode_u_32(arr[3]),
      framesPerBurst: dco_decode_i_32(arr[4]),
      bufferSizeFrames: dco_decode_i_32(arr[5]),
      bufferCapacityFrames: dco_decode_i_32(arr[6]),
      performanceMode: dco_decode_String(arr[7]),
      sharingMode: dco_decode_String(arr[8]),
      latencyMs: dco_decode_opt_box_autoadd_f_64(arr[9]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileSourceInfo dco_decode_file_source_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FileSourceInfo(
      id: dco_decode_u_32(arr[0]),
      durationS: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  EngineInfoWire? dco_decode_opt_box_autoadd_engine_info_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_engine_info_wire(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  SourceKindWire dco_decode_source_kind_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SourceKindWire.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EngineInfoWire sse_decode_box_autoadd_engine_info_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_engine_info_wire(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  EngineInfoWire sse_decode_engine_info_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_backend = sse_decode_String(deserializer);
    var var_api = sse_decode_String(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_32(deserializer);
    var var_framesPerBurst = sse_decode_i_32(deserializer);
    var var_bufferSizeFrames = sse_decode_i_32(deserializer);
    var var_bufferCapacityFrames = sse_decode_i_32(deserializer);
    var var_performanceMode = sse_decode_String(deserializer);
    var var_sharingMode = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_opt_box_autoadd_f_64(deserializer);
    return EngineInfoWire(
      backend: var_backend,
      api: var_api,
      sampleRate: var_sampleRate,
      channels: var_channels,
      framesPerBurst: var_framesPerBurst,
      bufferSizeFrames: var_bufferSizeFrames,
      bufferCapacityFrames: var_bufferCapacityFrames,
      performanceMode: var_performanceMode,
      sharingMode: var_sharingMode,
      latencyMs: var_latencyMs,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileSourceInfo sse_decode_file_source_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_durationS = sse_decode_f_32(deserializer);
    return FileSourceInfo(id: var_id, durationS: var_durationS);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  EngineInfoWire? sse_decode_opt_box_autoadd_engine_info_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_engine_info_wire(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SourceKindWire sse_decode_source_kind_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SourceKindWire.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_engine_info_wire(
    EngineInfoWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_engine_info_wire(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_engine_info_wire(
    EngineInfoWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.backend, serializer);
    sse_encode_String(self.api, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_32(self.channels, serializer);
    sse_encode_i_32(self.framesPerBurst, serializer);
    sse_encode_i_32(self.bufferSizeFrames, serializer);
    sse_encode_i_32(self.bufferCapacityFrames, serializer);
    sse_encode_String(self.performanceMode, serializer);
    sse_encode_String(self.sharingMode, serializer);
    sse_encode_opt_box_autoadd_f_64(self.latencyMs, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_source_info(
    FileSourceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_f_32(self.durationS, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_engine_info_wire(
    EngineInfoWire? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_engine_info_wire(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_source_kind_wire(
    SourceKindWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
