// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clip_cache`, `clip_key`, `decode_to_mono`, `get_or_decode`, `normalize_peak`, `pose_slot`, `resample_linear`, `state`, `tracker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClipCache`, `State`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

/// Start the realtime engine (cpal on desktop, oboe on Android).
/// Returns the negotiated stream parameters — the S1 latency data.
Future<EngineInfoWire> engineStart() =>
    RustLib.instance.api.crateApiEngineEngineStart();

Future<void> engineStop() => RustLib.instance.api.crateApiEngineEngineStop();

/// Live engine stats (latency may update on Android via timestamps).
EngineInfoWire? engineInfo() => RustLib.instance.api.crateApiEngineEngineInfo();

/// Push the fused-IMU quaternion (+ gyro rate in rad/s) into the engine.
/// Called at ~60 Hz from the sensor stream — keep it cheap and sync.
void setHeadPose({
  required double w,
  required double x,
  required double y,
  required double z,
  required double gx,
  required double gy,
  required double gz,
}) => RustLib.instance.api.crateApiEngineSetHeadPose(
  w: w,
  x: x,
  y: y,
  z: z,
  gx: gx,
  gy: gy,
  gz: gz,
);

/// Latch the current orientation as "forward".
void recenter() => RustLib.instance.api.crateApiEngineRecenter();

/// Prediction horizon in milliseconds (e.g. measured BT output latency).
void setPredictMs({required double ms}) =>
    RustLib.instance.api.crateApiEngineSetPredictMs(ms: ms);

/// L/R separation exaggeration: 1.0 = natural HRTF, up to 2.0.
/// Widens the rendered azimuth and deepens the far-ear shadow.
void setSpatialWidth({required double w}) =>
    RustLib.instance.api.crateApiEngineSetSpatialWidth(w: w);

/// Live spatial tuning for the calibration panel: azimuth exaggeration
/// (0.4-2.0), reverb wet send (0-0.6), extra far-ear cut span (dB).
void setSpatialParams({
  required double width,
  required double wet,
  required double ildDb,
}) => RustLib.instance.api.crateApiEngineSetSpatialParams(
  width: width,
  wet: wet,
  ildDb: ildDb,
);

/// Restrict head tracking to yaw (heading about gravity): tilts and
/// in-hand rolls stop swinging the scene's azimuth. Toggleable live.
void setYawOnly({required bool yawOnly}) =>
    RustLib.instance.api.crateApiEngineSetYawOnly(yawOnly: yawOnly);

Future<int> addSource({
  required SourceKindWire kind,
  required double x,
  required double y,
  required double z,
  required double gain,
}) => RustLib.instance.api.crateApiEngineAddSource(
  kind: kind,
  x: x,
  y: y,
  z: z,
  gain: gain,
);

void setSourcePosition({
  required int id,
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiEngineSetSourcePosition(
  id: id,
  x: x,
  y: y,
  z: z,
);

void setSourceGain({required int id, required double gain}) =>
    RustLib.instance.api.crateApiEngineSetSourceGain(id: id, gain: gain);

Future<void> removeSource({required int id}) =>
    RustLib.instance.api.crateApiEngineRemoveSource(id: id);

/// Warm the decode cache for a generated clip so the later
/// `add_file_source` is a cache hit — call as soon as the clip bytes
/// land, before the source's cue arrives. Async (worker pool); no-op
/// while the engine is off.
Future<void> prepareFileSource({required List<int> bytes}) =>
    RustLib.instance.api.crateApiEnginePrepareFileSource(bytes: bytes);

/// Play an audio file through the spatial pipeline. `bytes` is any
/// container symphonia probes (mp3/wav). Decode/resample runs OUTSIDE
/// the state lock and is cached — the lock is held only for id
/// allocation and the command push, so the 60 Hz pose and 30 Hz
/// position paths never stall behind an mp3 decode.
Future<FileSourceInfo> addFileSource({
  required List<int> bytes,
  required bool looping,
  required double x,
  required double y,
  required double z,
  required double gain,
}) => RustLib.instance.api.crateApiEngineAddFileSource(
  bytes: bytes,
  looping: looping,
  x: x,
  y: y,
  z: z,
  gain: gain,
);

/// Move a file source's playhead to `pos_s` seconds (clamped inside the
/// clip; seeking back into a finished one-shot replays it).
void seekSource({required int id, required double posS}) =>
    RustLib.instance.api.crateApiEngineSeekSource(id: id, posS: posS);

/// S2 ear-test render: a source orbiting the head, written to a WAV file.
Future<void> renderOrbitWav({
  required String path,
  required SourceKindWire kind,
  required double seconds,
  required double radiusM,
  required double elevDeg,
  required double periodS,
}) => RustLib.instance.api.crateApiEngineRenderOrbitWav(
  path: path,
  kind: kind,
  seconds: seconds,
  radiusM: radiusM,
  elevDeg: elevDeg,
  periodS: periodS,
);

/// Static binaural render at a fixed direction.
Future<void> renderStaticWav({
  required String path,
  required SourceKindWire kind,
  required double seconds,
  required double azDeg,
  required double elevDeg,
  required double distM,
}) => RustLib.instance.api.crateApiEngineRenderStaticWav(
  path: path,
  kind: kind,
  seconds: seconds,
  azDeg: azDeg,
  elevDeg: elevDeg,
  distM: distM,
);

/// Mirror of `sas_engine::rt::EngineInfo` for codegen (all-owned types).
class EngineInfoWire {
  final String backend;
  final String api;
  final int sampleRate;
  final int channels;
  final int framesPerBurst;
  final int bufferSizeFrames;
  final int bufferCapacityFrames;
  final String performanceMode;
  final String sharingMode;
  final double? latencyMs;

  const EngineInfoWire({
    required this.backend,
    required this.api,
    required this.sampleRate,
    required this.channels,
    required this.framesPerBurst,
    required this.bufferSizeFrames,
    required this.bufferCapacityFrames,
    required this.performanceMode,
    required this.sharingMode,
    this.latencyMs,
  });

  @override
  int get hashCode =>
      backend.hashCode ^
      api.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      framesPerBurst.hashCode ^
      bufferSizeFrames.hashCode ^
      bufferCapacityFrames.hashCode ^
      performanceMode.hashCode ^
      sharingMode.hashCode ^
      latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInfoWire &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          api == other.api &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          framesPerBurst == other.framesPerBurst &&
          bufferSizeFrames == other.bufferSizeFrames &&
          bufferCapacityFrames == other.bufferCapacityFrames &&
          performanceMode == other.performanceMode &&
          sharingMode == other.sharingMode &&
          latencyMs == other.latencyMs;
}

/// What a file source resolved to — the engine id plus the real decoded
/// length (a generator may return shorter audio than requested).
class FileSourceInfo {
  final int id;
  final double durationS;

  const FileSourceInfo({required this.id, required this.durationS});

  @override
  int get hashCode => id.hashCode ^ durationS.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileSourceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          durationS == other.durationS;
}

/// FRB-friendly mirror of SourceKind.
enum SourceKindWire { bee, rain, pad, tone, noise, click }
